version: "3.8"
services:
  zookeeper: 
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - broker-kafka  
    volumes:
      - zk-data:/var/lib/zookeeper/data    
      - zk-txn-logs:/var/lib/zookeeper/log

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    restart: on-failure
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1  
    ports:
      - "9092:9092"
      - "29092:2902"
    networks:
      - broker-kafka  
    volumes:
      - kafka-data:/var/lib/kafka/data

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8580:8080"
    restart: always
    depends_on:
     - kafka
    environment:
     - KAFKA_CLUSTERS_O_NAME=local
     - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
     - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    networks:
      - broker-kafka 

volumes:
  zk-data:
  zk-txn-logs:
  kafka-data:

networks:
  broker-kafka: